name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: my-step
        uses: actions/checkout@v3
      - run: ci/build-app.sh
      - name: test
        run: ci/unit-test-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
